### ISSUE TITLE
AnylineJS setup error: undefined

### ISSUE THREAD

**Issue by Mikilll94** [Anyline/anyline-ocr-anylinejs-module#2]
When running the sample project from this repository I am getting the following errors:
![Screenshot 2020-05-26 at 12 07 34](https://user-images.githubusercontent.com/17653648/82888351-7e61f780-9f49-11ea-980f-1c29114644a3.png)

**Comment by garygrossgarten** [comment]
Getting the same issue implementing v20 (also I couldn't find a working version) from cdn. ShowCircle is spinning and once I start the scan the camera feed successfully streams to my container element. The two errors above are getting thrown while starting the camera. 

I haven't been able to get any actual scan results.

**Comment by davlhd** [comment]
Hello, currently AnylineJS has a bug where it does not correctly issue licensing errors. This is most likely a licensing issue. The license included only works on 127.0.0.1 and localhost.

**Comment by garygrossgarten** [comment]
@davlhd Thanks for your quick reply. I'm developing on localhost though.

**Comment by garygrossgarten** [comment]
@davlhd I got it to work switching from localhost to 127.0.0.1.🎉

**Comment by Mikilll94** [comment]
@davlhd 
I am running the project from this repo on localhost, but on 7777 port. Additionally, I am not using HTTPS for my localhost connection. Does it matter? Could this be a cause of my problem?

**Comment by garygrossgarten** [comment]
> @davlhd I got it to work switching from localhost to 127.0.0.1.🎉

@Mikilll94 maybe you could try out `127.0.0.1:7777`. The port shouldn't be a problem. I'm running on 8100.

**Comment by Mikilll94** [comment]
@garygrossgarten 
Thanks. I followed your advice and replaced localhost with 127.0.0.1 and now it is working 🎉

**Comment by mklan** [comment]
@Mikilll94 yes try 127.0.0.1 it translates to localhost, but currently thee licensing system does not accept localhost. Missing https could lead to problems on some browsers like Safari,since Webworker need to be run in a save environment, even when running locally.
