### ISSUE TITLE
MRZ scan does not respond with result

### ISSUE THREAD

**Issue by enterframe** [Anyline/anyline-ocr-anylinejs-module#23]
By using the AnylineJS demo at https://js.anyline.com/demo/index.html, the MZR scan does sometimes (1 of 5) not respond with a result and there is no user-feedback at all.
In case of no result the blue dots are no more showing up so it seams that the scan is no longer in progress.
That is also the case by running the demo locally.

Version: 40.1.0

**Comment by davlhd** [comment]
Hello,

I have been looking into this issue and there will be a fix in the next release. Thank you for filing a bug ticket.
