### ISSUE TITLE
Integration of Anyline into next.js / SSR

### ISSUE THREAD

**Issue by ciruz** [Anyline/anyline-ocr-anylinejs-module#28]
Hey,

I'm trying to integrate Anyline into an existing next.js / SSR project, is there maybe an example for Anyline and something similar like [next.js](https://github.com/vercel/next.js/) (with/without SSR)?

I get Anyline to work partially, depending on the integration method I use (Dynamic Imports, Next Script, useEffect, etc.), I can also access the camera / webcam and even start the scanning process, but I can never access any results, since there is no ``onResults`` method. 

Thank you

**Comment by ciruz** [comment]
I got it to work with a dynamic import.

**Comment by Candoyeya** [comment]
> I got it to work with a dynamic import.

Can you share your implementation? I also need to solve problems with nextjs
