### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')

### ISSUE THREAD

**Issue by Mikilll94** [Anyline/anyline-ocr-anylinejs-module#3]
When running the sample project from this repository on Safari on iPhone 11, I got this error:

![Screenshot 2020-05-26 at 17 02 07](https://user-images.githubusercontent.com/17653648/82916678-a31e9500-9f72-11ea-9529-1716b730d8a2.png)

And the camera view is not opening.

**Comment by mklan** [comment]
Are you running you web-server using ssl? Safari needs a secure connection in order to enable the camera.

**Comment by Mikilll94** [comment]
@mklan 
My web server is running on 127.0.0.1 (localhost). Do I need SSL cert for the 127.0.0.1 address?

**Comment by mklan** [comment]
@Mikilll94 yes you would need to create some self signed certificates and run a local web-server using for example:

`npx http-server -S -C cert/cert.pem -K cert/key.pem -P 3000`

We plan to add local certs and a script to run a localserver to the demo in the next release
