### ISSUE TITLE
Issues with Safari

### ISSUE THREAD

**Issue by garygrossgarten** [Anyline/anyline-ocr-anylinejs-module#4]
Hey there,

I'm using v21 of Anyline.

I'm getting 
```json
{"message": "AnylineJS setup error: undefined"," code": 20001}
```
and 
```json
{"message": "AnylineJS processing error: Out of bounds memory access (evaluating 'n.asm.dynCall_viii.apply(null,arguments)')", "code": 20003}
```

in Safari (iOS and macOS), although everything works as expected in Chrome (macOS and Android). I'm getting the error in production and on my local machine  [Live Demo here](https://anyline.inteligy.services/demo). Any idea what could be causing this?

Thanks!

**Comment by davlhd** [comment]
Hello,

which version are you using? This error indicates that something is wrong with your license.
The license included in the demo is only valid for 127.0.0.1 and localhost.

**Comment by garygrossgarten** [comment]
Hey there,

I'm using v21. Same happens with v20. I don't think it's an issue with the license because it's working in other browsers.

**Comment by garygrossgarten** [comment]
It's working after including the anyline datafiles correctly in my angular application. I didin't specify `anylinePath` to the data files but only including the js script. 

Loading `anylinejs.wasm.gz ` from https://js.anyline.com/v21/anylinejs/anylinejs.wasm.gz instead from a project directory seemed to be the problem for me in Safari as opposed to Chrome.
