### ISSUE TITLE
Please support localhost in license

### ISSUE THREAD

**Issue by inspirexs** [Anyline/anyline-ocr-anylinejs-module#44]
Hi Guys, can you please update the license so that it supports localhost and not just 127.0.0.1?

**Comment by ciruz** [comment]
Hey @inspirexs,

looks like I'm not the only one with this problem.
I think there was a change since the same licsense don't work anymore.

I'll contact the support for this.

**Comment by peterAnyline** [comment]
Thank you for raising this issue. In order for us to effectively gather all the information to properly handle your request, may I kindly ask you to submit a ticket via https://anyline.atlassian.net/servicedesk/customer/portal/2/group/-1. Thank you for understanding.
