### ISSUE TITLE
Setting cancelOnResult to false does not trigger anyline.onResult

### ISSUE THREAD

**Issue by ponki-d-monkey** [Anyline/anyline-ocr-anylinejs-module#45]
Hi, we're upgrading Anyline from v41.0.0 to v42.3.1. Unfortunately, `cancelOnRequest` is not working like it used to when scanning a QR code.

We have a use case where we want users to stay on the scanning page after scanning a QR code and let them scan another one. It was working on v41.0.0, but in the latest version it's not. I can see that it's still scanning (the `anyline.onScannedBarcode` callback is triggered), but `anyline.onResult` is no longer triggered after the first scan.

**Comment by peterAnyline** [comment]
Thank you for raising this issue. In order for us to effectively gather all the information to properly handle your request, may I kindly ask you to submit a ticket via https://anyline.atlassian.net/servicedesk/customer/portal/2/group/-1. Thank you for understanding.

**Comment by peterAnyline** [comment]
Thank you for raising this issue. In order for us to effectively gather all the information to properly handle your request, may I kindly ask you to submit a ticket via https://anyline.atlassian.net/servicedesk/customer/portal/2/group/-1. Thank you for understanding.
