### ISSUE TITLE
anyline.onResult callback undefined

### ISSUE THREAD

**Issue by oliverlukesch** [Anyline/anyline-ocr-anylinejs-module#50]
Dear Anyline team,

We're having the following issue:

### Setup:

* WebSDK version: 42.5.0
* Other relevant libs: React 18.2.0, NextJs 13.4.19
* Installed via `npm i @anyline/anyline-js`
* Imported via `import {Types as AnylineTypes, init} from '@anyline/anyline-js'`

### Sample code:

```ts
'use client'

import React, {memo, useEffect, useRef} from 'react'

import {Types as AnylineTypes, init} from '@anyline/anyline-js'

// taken from: https://github.com/Anyline/anyline-ocr-anylinejs-module/blob/master/demo/license.js
const demoLicense = 'ewogICJsaWNlbnNlS2V5VmVyc2lvbiI6ICIzLjAiLAogICJkZWJ1Z1JlcG9ydGluZyI6ICJvbiIsCiAgIm1ham9yVmVyc2lvbiI6ICIzNyIsCiAgInNjb3BlIjogWwogICAgIkFMTCIKICBdLAogICJtYXhEYXlzTm90UmVwb3J0ZWQiOiAxNCwKICAiYWR2YW5jZWRCYXJjb2RlIjogdHJ1ZSwKICAicGxhdGZvcm0iOiBbCiAgICAiSlMiCiAgXSwKICAic2hvd1dhdGVybWFyayI6IGZhbHNlLAogICJ0b2xlcmFuY2VEYXlzIjogMzAsCiAgInZhbGlkIjogIjIwMjQtMTAtMTAiLAogICJqc0lkZW50aWZpZXIiOiBbCiAgICAianMuYW55bGluZS5jb20iLAogICAgIjEyNy4wLjAuMSIsCiAgICAibG9jYWxob3N0IiwKICAgICIxOTIuMTY4LioiCiAgXQp9CnV4SUd2ejBjTEMyVG0yVkNSc0RXeGdyMmdSVzlOaDA2am83TlJJWS8ycHcrbDF6TnZvcGdsRE1PQWl6RjJEUmYKQVJ3OURtTlFKRGxnbUUxWG5ZWitSVFdGNFAvMDljMTlrVTFMN0dicTB6REoyT2hvYTZENFhROFprbFMwTXVpUQpLdVJUdlFVZTh5bGVJSXJSSzhrTm85WW0xaER4VmcvWHpDUThRSmM3TUNWMHBvQzlRbVYyZWVwaTNBbUNYclZaCnVvRFNob3B6bEoxRzdOdEh0QUxEKzVUeWpmb2ZTbVpkdkV0RmEwMTI2cG1WZDNOTlJJWXlUa0tRdXBpREM0eHkKak9NSVhsalBYUDBwajlHeGoyTHdKQWZLazRxcGw0RG5KejFJWldrWXhramhSc1lVUUxjTzRoaVozeUxMemxrdQpJTGp6eDh3L2NtUGVmYzY4WEh0bERnPT0K'

export default memo(function Anyline({
  onSuccess,
  onError,
}: {
  onSuccess: (result: AnylineTypes.AnylineJSResult) => void
  onError: (error: Error) => void
}) {
  console.log('render Anyline')

  const anylineRootRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (anylineRootRef.current) {
      console.log('init Anyline')

      const anyline = init({
        preset: 'universalid_dl_at_de',
        config: {
          mirrorOnDesktop: true,
        },
        license: demoLicense,
        element: anylineRootRef.current,
        debugAnyline: true,
        anylinePath: `/anylinejs`,
      })

      anyline.startScanning().catch(onError)

      console.log('onResult callback:', anyline.onResult)
      console.log(anyline)
    }
  }, [onSuccess, onError])

  return (
    <div
      ref={anylineRootRef}
      style={{position: 'fixed', left: 0, top: 0, height: '100%', width: '100%', zIndex: 9999}}
    />
  )
})
```

### What works:

* The SDK loads
* The scanning overlay gets displayed
* The camera starts
* Getting useful information through the debug log (including scanning results)

### What does not work:

* The `anyline.onResult` callback appears to be undefined

* If we log the callback using `console.log('onResult callback:', anyline.onResult)`, we get the following output :`onResult callback: undefined`

* If we inspect the object, no callback is to be found (please see the screenshot below):

<img width="703" alt="Screenshot 2023-09-13 at 12 29 54" src="https://github.com/Anyline/anyline-ocr-anylinejs-module/assets/5070919/e15afd1c-3997-433b-8d59-12184bd06301">

Your support is appreciated, many thanks!

**Comment by ciruz** [comment]
@oliverlukesch FYI, we have implemented anyline.js in our next.js project, but we are using an older version of `anyline.js` (v41.0.1). After upgrading to anyline.js version 41.0.2 or any 42.0.X release, it stopped working for us, and this issue occurred without any other code changes.

Unfortunately, we haven't had the time to attempt an update to a newer version of anyline since then.

We also encountered a problem where the scanner initializes successfully, and we receive various debugger messages in the console. The overlay with the cutout appears as expected, but the actual scanning process never starts. Sounds like the same problem you are facing.

**Comment by JonasLaux** [comment]
Hey @oliverlukesch, thanks for reaching out. Sorry for the inconvenience, but you already have 95%. The `onResult` function doesn't come from the SDK, though you have to set it, so you can enrich it with whatever business logic you have. That means, if you do something like:

`
...  
const anyline = init({
...
});
   
 anyline.onResult = (result) => {
    alert(result) // do whatever business logic here
 }

  anyline.startScanning().catch(onError);
  ...
  `
The SDK will trigger the `onResult` everytime it has a result for you
