### ISSUE TITLE
Doesn't work on IPhone and Mac -  Safari

### ISSUE THREAD

**Issue by ystoliarchuk** [Anyline/anyline-ocr-anylinejs-module#6]
I added anylinejs to the website with a trial anylicense fro testing how it works
From desktop camera(include via USB) it works, but from iPhone 8+ I see errors
**How I use:**

```
var viewConfig = {
    outerAlpha: 0.5,
    scanMode: 'AUTO_ANALOG_DIGITAL_METER',
    cutouts: [
        {
            cutoutConfig: {
                // style: 'rect',
                maxWidthPercent: '80%',
                alignment: 'top_half',
                ratioFromSize: {
                    width: 300,
                    height: 250,
                },
                width: 720,
                strokeWidth: 2,
                cornerRadius: 4,
                strokeColor: 'FFFFFFFF',
                feedbackStrokeColor: '0099FF',
            },
            scanFeedback: {
                style: 'contour_point',
                strokeColor: '0099FF',
                fillColor: '300099FF',
                strokeWidth: 2,
                cornerRadius: 4,
                animation: 'none',
            },
        },
    ],
};
var anylicense = '*****my license****';
var myAnyline = init({
    preset: 'meter',
    viewConfig,
    license: anylicense,
    element: this.root,
});

myAnyline.startScanning();
myAnyline.onError = ({code, message}) => {
    console.log('error: ', message);
    alert(message);
};
myAnyline.onResult = function (result) {
    alert('Anyline has result: ', result[0].text);
};
```
**Reproduce:**
Go to site https://devchatbuilder.tk/ on the bottom added button "Open scan" -> click on the button -> wait 5 second -> alert with errors:
1 - AnylineJS setup error undefined
2 - AnylineJS processing error: Out of bounds memory access (evaluating 'n.asm.dynCall_viii.apply(null,arguments)'

Any suggestions are welcomed

**Comment by davlhd** [comment]
Hello,

please try hosting it on your server by passing a `anylinePath: anylinejsFolderPath` and putting the files on your server.
Also please use debugAnyline: true and post the debug output.

**Comment by ystoliarchuk** [comment]
Hi @davlhd  thanks for replay
I have downloaded file and included it in anylinePath, but I get an error with object window
![error](https://user-images.githubusercontent.com/47854450/86766917-dc5b2200-c053-11ea-95f5-e7a913335a6c.jpg)

**Comment by ystoliarchuk** [comment]
Also, it doesn't works from mac - safari, but mac- chrome works correctly

**Comment by ystoliarchuk** [comment]
This version works for me but broke scroll on site http://js.anyline.com/v20/anylinejs.zip
